{% extends '../../../../layout/club.html' %}

{% block pageTitle %}29 Augustus 2014 - Club{% endblock %}

{% block content %}
<div class="row">
	<h2>Part Time Punks</h2>
	<p>21:00 ZO 29/<a href="{{ siteUrl }}/club/2014/08" class="tiny button secondary">08</a></p>
</div>
{% include '../../../../artists/parttimepunks.html' %}
<div class="row">
	<h4>dj The Craze & Baarmoeder Dj's</h4>
</div>
{% endblock %}