{% extends '../../../../layout/club.html' %}

{% block pageTitle %}14 september 2014 - Club{% endblock %}

{% block content %}
<div class="row">
	<h2>Action beat <small>(UK)</small></h2>
	<p>21:00 ZO 14/<a href="{{ siteUrl }}/club/2014/09" class="tiny button secondary">09</a></p>
</div>
{% include '../../../../artists/action_beat.html' %}
<div class="row">
	<h2>G.W.SOK <small>(NL)</small></h2>
	<p>22:00</p>
</div>
{% include '../../../../artists/g.w.sok.html' %}
{% endblock %}