{% extends '../../../../layout/club.html' %}

{% block pageTitle %}5 september 2014 - Club{% endblock %}

{% block content %}
<div class="row">
	<h2>Kinky Metal: Back in black pillars</h2>
	<p>21:00 VR 05/<a href="{{ siteUrl }}/club/2014/09" class="tiny button secondary">09</a></p>
</div>
{% include '../../../../artists/backinblackpillars.html' %}
<div class="row">
	<h4>dj nachtland</h4>
</div>
{% endblock %}