{% extends '../../../../layout/club.html' %}

{% block pageTitle %}17 oktober 2014 - Club{% endblock %}

{% block content %}
<div class="row">
	<h2>Jamsessie - Den hoed workshop</h2>
	<p>21:00 ZO 17/<a href="{{ siteUrl }}/club/2014/10" class="tiny button secondary">10</a></p>
</div>
{% include '../../../../artists/den_hoed_workshop.html' %}
<div class="row">
	<h4>dj Cablesandwich</h4>
</div>
{% endblock %}