{% extends '../../../../layout/club.html' %}

{% block pageTitle %}26 september 2014 - Club{% endblock %}

{% block content %}
<div class="row">
	<h2>Kinky world: Zebras are timeless</h2>
	<p>21:00 VR 26/<a href="{{ siteUrl }}/club/2014/09" class="tiny button secondary">09</a></p>
</div>
{% include '../../../../partials/artists/zebras_are_timeless.html' %}
<div class="row">
	<h4>dj Desperado & dj Snoet</h4>
</div>
{% endblock %}