{% extends '../../../../layout/club.html' %}

{% block pageTitle %}31 oktober 2014 - Club{% endblock %}

{% block content %}
<div class="row">
	<h2>Kinky metal halloween : Stahlsarg <small>(UK)</small></h2>
	<p>21:00 WO 31/<a href="{{ siteUrl }}/club/2014/10" class="tiny button secondary">10</a></p>
</div>
{% include '../../../../artists/stahlsarg.html' %}
<div class="row">
	<h4>dj Massiv Agressiv & Cyco Jello</h4>
</div>
{% endblock %}