{% extends '../../../../layout/club.html' %}

{% block pageTitle %}24 oktober 2014 - Club{% endblock %}

{% block content %}
<div class="row">
	<h2>Last emotions V: We are ooh people</h2>
	<p>21:00 VR 24/<a href="{{ siteUrl }}/club/2014/10" class="tiny button secondary">10</a></p>
</div>
{% include '../../../../artists/we_are_ooh_people.html' %}
<div class="row">
	<h4>dj The craze & dj Angel</h4>
</div>
{% endblock %}