{% extends '../../../../layout/club.html' %}

{% block pageTitle %}20 september 2014 - Club{% endblock %}

{% block content %}
<div class="row">
	<h2>Baby fire</h2>
	<h3>special guest: Eve Libertine/Crass</h3>
	<p>21:00 ZA 20/<a href="{{ siteUrl }}/club/2014/09" class="tiny button secondary">09</a></p>
</div>
{% include '../../../../partials/artists/baby_fire.html' %}
<div class="row">
	<h4>dj Stijn Kwanten</h4>
</div>
{% endblock %}