{% extends '../../../../layout/club.html' %}

{% block pageTitle %}4 september 2014 - Club{% endblock %}

{% block content %}
<div class="row">
	<h2>Hiphopstraatgebeuren</h2>
	<p>21:00 DO 04/<a href="{{ siteUrl }}/club/2014/09" class="tiny button secondary">09</a></p>
</div>
{% include '../../../../artists/hiphopstraatgebeuren.html' %}
<div class="row">
	<p>Tjudee / Dilemma / Martijn Nelen / Mon (SG Records)</p>
</div>
{% endblock %}