{% extends '../../../layout-club.html' %}

{% block content %}
<div class="row">
	<h2>Augustus 2014</h2>
</div>
<div class="row">
	<ul class="small-block-grid-6 medium-block-grid-3">
		<li>
			<a href="{{ siteUrl }}/club/2014/08/29">
				<h3>Part Time punks</h3>
			</a>
		</li>
		<li>
			<a href="{{ siteUrl }}/club/2014/08/30">
				<h3>Elements</h3>
			</a>
		</li>
		<li>
			<a href="{{ siteUrl }}/club/2014/08/31">
				<h3>Gâtechien</h3>
			</a>
		</li>
	</ul>
</div>
{% endblock %}