{% extends '../../../../layout/club.html' %}

{% block pageTitle %}3 september 2014 - Club{% endblock %}

{% block content %}
<div class="row">
	<h2>Discodeath <small>(IT)</small></h2>
	<p>21:00 WO 03/<a href="{{ siteUrl }}/club/2014/09" class="tiny button secondary">09</a></p>
</div>
{% include '../../../../partials/artists/discodeath.html' %}
<div class="row">
	<h4>dj Fakteur</h4>
</div>
{% endblock %}