{% extends '../../../../layout/club.html' %}

{% block pageTitle %}19 september 2014 - Club{% endblock %}

{% block content %}
<div class="row">
	<h2>Kinky surf night: Daikaiju <small>(VS)</small></h2>
	<p>21:00 VR 19/<a href="{{ siteUrl }}/club/2014/09" class="tiny button secondary">09</a></p>
</div>
{% include '../../../../partials/artists/daikaiju.html' %}
<div class="row">
	<h4>dj Jenz</h4>
</div>
{% endblock %}