{% extends '../../../../layout/club.html' %}

{% block pageTitle %}9 oktober 2014 - Club{% endblock %}

{% block content %}
<div class="row">
	<h2>Transfigure <small>(UK)</small></h2>
	<p>21:00 DO 09/<a href="{{ siteUrl }}/club/2014/10" class="tiny button secondary">10</a></p>
</div>
{% include '../../../../partials/artists/transfigure.html' %}
<div class="row">
	<h4>KS galactica dj Leen vs dj Surprise act</h4>
</div>
{% endblock %}